### PR TITLE
Remove the vpcctl binary from the IBM cloud controller manager

### PR DESCRIPTION
**Pull request by jckasper**
This is a preview of an internal PR that is still being tested

-- DO NOT MERGE --

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Is there any update on the status of the internal tests? This looks pretty good so I'm hoping we can migrate to this at some point in the near future

**Comment by jckasper** [comment]
@JoelSpeed The internal VPC regression tests completed successfully back in November.  
Waiting on code review/sign off from Richard Theis and the IBM CCM/update squad.
Hopefully the upstream change can get reviewed by Richard in early January.

**Comment by jckasper** [comment]
@JoelSpeed  The upstream PR has been fully tested since before Thanksgiving. However, Richard Theis does not like / agree with the design change and he will not review or approve the upstream PR. It looks like your current, ugly git submodule build process is going to be here indefinitely.

**Review by rtheis — CHANGES_REQUESTED** [review]
@JoelSpeed John's statement is not accurate.  We are blocked on disagreement with architectural changes here.

**Review by rtheis — CHANGES_REQUESTED** [review]
Not approved

**Comment by jckasper** [comment]
I have to give credit where credit is due.  The whole idea to switch the VPC controller logic from a binary over to GO module/library came from the IKS networking team in Hungry.  They provided the first PRs to convert over to GO module/library back on: 6/18/2001.  I was skeptical at first, but looking back, this was great, unique idea that I had never even considered before. 

Well over 50+ PRs were done during the summer and into the fall months to complete the work to get the repo setup so that it could be called as a GO library/module.  The design document to switch CCM to invoke VPC LB via GO module/library call was created in September 2021. 

The first upstream PR to switch CCM to invoke VPC controller via GO module/library call was done back on: 10/21/2021.  This PR used the initial v0.1.0 release version of the VPC controller.  Despite this being the very first git release of the VPC controller, it did include all of the requested/required VPC IPI changes (known at that time).

Over the next few weeks, the CCM to VPC LB interface was tested, updated, optimized, re-tested, and simplified. A second upstream PR was created on: 11/15/2021.  This PR used the v0.3.0 version of the VPC controller.  More testing and then a week later on 11/22/2021,  the PR was refreshed to use the: v0.3.1 version of the VPC controller.  Lots more testing.

On 12/1/2021, this PR was created based on that second upstream PR.  Roughly 95% of what was done in the upstream PR was included in this PR.

On 1/5/2022, the VPC controller was updated to v0.4.0. I probably did not need to update the minor release.  There were no functional changes in this update. It was just a refresh of the dependencies.  (The last functional change/bug fix was back on 11/11/2021 with the v0.3.0 version.)

Yesterday, 1/25/2022, I updated this PR to use the new v0.4.0 version of the VPC controller.

**Pull request closed without merging**
