### PR TITLE
OCPCLOUD-2046: Manual rebase kubernetes 1.27 and go 1.20

### PR DESCRIPTION
**Pull request by RadekManak**
This PR is based on the latest rebasebot rebase. I have squashed some of the commits and cherry-picked the ART go 1.20 commit on top.

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
Hi @RadekManak , We also need to update https://github.com/openshift/cloud-provider-powervs repository similar to this, 

cloud-provider-powervs repo shares most of the code with this repo with only few additional commits to support Power VS platform, Please let us know the plan or approach to update repo.

**Comment by RadekManak** [comment]
@Karthik-K-N We expect you to be taking care of powervs repo. There is open rebasebot PR https://github.com/openshift/cloud-provider-powervs/pull/24, It looks like it needs some manual fixes. You should be able to check out the rebasebot PR, update it and create PR with your fixes.

Looks like release-4.13 was not updated to use kubernetes 1.26 either. It is likely okay to not update release-4.13 and only update main, but if you want to fix it, you will have to run[ rebasebot manually](https://github.com/openshift-eng/rebasebot/blob/main/README.md#examples-of-usage) or do the rebase yourself. 

Feel free to message me on Slack if you need help.

**Pull request merged**
